Repository mattermost-community/mattermost-plugin-jitsi, pull requests merged in 2020-06, with the labels that each got.

#74 Document new features
  README.md
  plugin.json
Labels: 4: Reviews Complete

#54 Add note on Jesús helping as a maintainer of the repo
  CODEOWNERS
  README.md
Labels: 4: Reviews Complete

#93 Make random numbers generation cryptographically secure
  server/randomNameGenerator.go
Labels: 4: Reviews Complete

#81 Server side i18n
  .gitignore
  assets/i18n/active.en.json
  assets/i18n/active.es.json
  build/custom.mk
  go.mod
  go.sum
  server/command.go
  server/i18n.go
  server/manifest.go
  server/plugin.go
  webapp/src/manifest.ts
Labels: 2: Dev Review, 3: QA Review

#94 Addressing PR comments in the review for marketplace
  webapp/src/actions/index.ts
  webapp/src/components/conference/conference.tsx
  webapp/src/components/conference/index.ts
  webapp/src/components/post_type_jitsi/index.ts
  webapp/src/components/post_type_jitsi/post_type_jitsi.tsx
  webapp/src/index.tsx
  webapp/src/types.ts
Labels: 4: Reviews Complete

#100 Remove override user/icon on for new meeting message
  server/plugin.go
Labels: 3: QA Review

#92 Fix links on RN
  server/plugin.go
Labels: 3: QA Review

#96 Add a random text at the end of the custom meeting topic
  server/plugin.go
Labels: 3: QA Review

#95 Making personal meeting name random
  server/plugin.go
  server/randomNameGenerator.go
Labels: 3: QA Review

#90 Fix name_scheme words
  plugin.json
  server/api.go
  server/command.go
  server/command_test.go
  server/manifest.go
  server/plugin.go
  webapp/src/manifest.ts
Labels: 3: QA Review

#101 Moving naming schema settings up in the config panel
  plugin.json
  server/manifest.go
  webapp/src/manifest.ts
Labels: 4: Reviews Complete

#104 Adding minimized by default and low quality on minimized
  webapp/src/components/conference/conference.tsx
Labels: 3: QA Review

#83 Set meet.jit.si as default jitsi server
  plugin.json
  server/api.go
  server/configuration.go
  server/manifest.go
  server/plugin.go
  webapp/src/manifest.ts
Labels: 3: QA Review

#107 Fix security concern on getting javascript from the outside
  assets/external_api.js
  plugin.json
  server/api.go
  server/configuration.go
  server/manifest.go
  webapp/src/manifest.ts
Labels: 3: QA Review

#117 Add badges
  README.md
Labels: 2: Dev Review

#118 Fix typo
  README.md
Labels: 2: Dev Review

#111 Fix problem copying link with JWT
  webapp/src/components/post_type_jitsi/post_type_jitsi.tsx
Labels: 3: QA Review

#116 Add german translation
  .gitattributes
  assets/i18n/active.de.json
  build/manifest/main.go
  server/manifest.go
  webapp/i18n/de.json
  webapp/i18n/index.ts
  webapp/src/manifest.ts
Labels: 4: Reviews Complete

#119 Fix post message handling
  webapp/src/components/conference/conference.tsx
Labels: 2: Dev Review

#125 Clarify that some plugin settings can be overridden by users
  plugin.json
Labels: 1: PM Review, 3: QA Review

#128 Jasonblais patch 1 updated
  assets/i18n/active.de.json
  assets/i18n/active.en.json
  assets/i18n/active.es.json
  assets/i18n/active.fr.json
  server/command.go
  server/command_test.go
Labels: 4: Reviews Complete

#105 Bump version to 2.0.0
  plugin.json
  server/manifest.go
  webapp/src/manifest.ts
Labels: 4: Reviews Complete
